# This workflow will build a golang project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-go

name: Go

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:

  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: Set up Go
      uses: actions/setup-go@v3
      with:
        go-version: 1.19
    
    - name: setup swag
      run: go get -u github.com/swaggo/swag/cmd/swag@v1.7.0
    
    - name: Donwload dependecies libraries
      run: go mod download
      
    - name: Generate swag documents
      run: |
        export PATH=$PATH:$(go env GOPATH)/bin
        swag init -d . -g ../cmd/main.go -o ./docs

    - name: Build
      run: go build -v ./...

    - name: Test
      run: go test -v ./...
